Feature/webuy
buhills/we-buy pull request #1
Opened 2023-11-09 13:06 UTC by buhills

2023-11-10 10:03 UTC, nganifaith requested changes
Great job so far @buhills.  I love the work you've put in. However, we are not yet there.

**Changes requested**

- [ ] your font size is too big
- [ ] you page is leaking
- [ ] avoid using fixed margins and padding as much as possible. Use relative values like auto, %, em, rem, vw, vh.
- [ ] complete your footer
- [ ] center you text in every container.

2023-11-10 10:03 UTC, nganifaith commented on assets/styles/styles.css
> +.footer-container-logo-txt {
provide some margins to your section

2023-11-13 18:00 UTC, buhills commented on index.html
> +        <div class="webuy">
copied

2023-11-13 18:01 UTC, buhills commented on index.html
> +      <div class="headercontainer-header">
copied

2023-11-14 07:52 UTC, buhills commented on index.html
> +    <footer class="footer-container">
Done

2023-11-18 10:21 UTC, merged

2023-11-18 19:49 UTC, nganifaith reviewed
Great job @buhills. still have some work to do.

- [ ] increase the font size of your footer element
- [ ] lastest news section reduce the gap and increase the card size
- [ ] header out of place
- [ ] why sell with us section is out of place. Font size shouldn't be bold

2023-11-18 21:01 UTC, buhills commented
> Great job @buhills. still have some work to do.
> 
> - [ ] increase the font size of your footer element
> - [ ] lastest news section reduce the gap and increase the card size
> - [ ] header out of place
> - [ ] why sell with us section is out of place. Font size shouldn't be bold

Copied ma'am 
Thanks